name: Setup Node and pnpm
description: Setup pnpm and Node.js, then install dependencies with pnpm.
inputs:
  node-version:
    description: Node.js version to use.
    required: true
  pnpm-version:
    description: pnpm version to use.
    required: true
  install-command:
    description: Command used to install dependencies.
    required: false
    default: pnpm install --frozen-lockfile --prefer-offline
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Install dependencies
      shell: bash
      run: ${{ inputs.install-command }}
